### ISSUE TITLE
厉害了

### ISSUE THREAD

**Issue by c53hzn** [beijingjazzpanda/cpu-monitor-plot#1]
郭哥好啊~
这个项目厉害了👍
但是我不太会看😢

**Comment by beijingjazzpanda** [comment]
你下載下來，裡面有sample file，你打開cpu.html或者thread.html，然後上傳sample file就可以看到了
________________________________
From: Jenny ***@***.***>
Sent: Friday, July 23, 2021 11:16:53 AM
To: beijingjazzpanda/cpu-monitor-plot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [beijingjazzpanda/cpu-monitor-plot] 厉害了 (#1)


郭哥好啊~
这个项目厉害了👍
但是我不太会看😢
